# Generated by Django 3.0.5 on 2020-05-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='codename',
        ),
    ]
